project '../beingexpat.xcodeproj'
platform :ios, '8.1'
target "beingexpat" do
    pod 'Google/SignIn'
    
    
    pod 'Firebase/AdMob'
    pod 'Firebase/Auth'
    pod 'Firebase/Crash'
    pod 'Firebase/Database'
    pod 'Firebase/Invites'
    pod 'Firebase/RemoteConfig'
    pod 'Firebase/Storage'
    pod 'Firebase/Core'
    
    use_frameworks!
    
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'FacebookShare'
    
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'

end
